git clone https://github.com/yamanefkar/Turk-Sploit
git clone https://github.com/yamanefkar/Turk-Sploit-Demo
git clone https://github.com/htr-tech/zphisher.git
git clone https://github.com/gkbrk/slowloris.git
git clone https://github.com/bdblackhat/admin-panel-finder.git
git clone https://github.com/Ranginang67/DarkFly-Tool.git
git clone https://github.com/LimerBoy/Impulse.git
git clone https://github.com/yamanefkar/T-U-R-K.git
git clone https://github.com/noob-hackers/m-wiz.git
git clone https://github.com/Cabbagec/termux-ohmyzsh.git
git clone https://github.com/adi1090x/termux-desktop.git
git clone https://github.com/fuck3erboy/instahack.git
git clone https://github.com/AngelSecurityTeam/Cam-Hackers.git
git clone https://github.com/ExpertAnonymous/PhoneInfoga.git
git clone https://github.com/reinxceed2/wpbf.git
git clone https://github.com/DeepSociety/koroni.git
git clone https://github.com/noob-hackers/grabcam.git
git clone https://github.com/sqlmapproject/sqlmap.git
git clone https://github.com/Manisso/fsociety.git
git clone https://github.com/ByCh4n/BCHackTool.git
git clone https://github.com/Bitwise-01/Instagram-.git
git clone https://github.com/Mebus/cupp.git
git clone https://github.com/IlayTamvan/Report.git
git clone https://github.com/UndeadSec/EvilURL.git
git clone https://github.com/Gameye98/Lazymux.git
git clone https://github.com/s0md3v/Breacher.git
git clone https://github.com/kuburan/txtool.git
git clone https://github.com/Rajkumrdusad/MyServer.git
git clone https://github.com/Rajkumrdusad/IP-Tracer.git
git clone https://github.com/TUANB4DUT/TOOLSINSTALLERv3
git clone https://github.com/Gameye98/santet-online
git clone https://github.com/404rgr/spamerCALL
git clone https://github.com/marioyhzkiell/bugreport.git
git clone https://github.com/Lulz3xploit/LittleBrother
git clone https://github.com/j3ssie/Osmedeus
git clone https://github.com/nasirxo/AK47
git clone https://github.com/TunisianEagles/winspy.git
git clone https://github.com/PangeranAlvins/Repot3
git clone https://github.com/m4rktn/zeroeye
git clone https://github.com/INDOnimous/Card-Number
git clone https://github.com/mbest99/gametool
git clone https://github.com/thelinuxchoice/blackeye
git clone https://github.com/AngelSecurityTeam/GatheTOOL
git clone https://github.com/bhikandeshmukh/MapEye.git
git clone https://github.com/yan4ikyt/webhack/
git clone https://github.com/batyarimskiy/vkRaidbot
git clone https://github.com/TechnicalMujeeb/TM-scanner
git clone https://github.com/danielmiessler/SecLists
git clone https://github.com/Pix-head/MODoS
